const Homeproduct=
[
    {
        id:1,
        Name: 'product1',
        price:'200',
        image:'image/p1.jfif',
        cat:'table',
        type:'new',
    },
    {
        id:2,
        Name: 'product2',
        price:'60',
        image:'image/p2.jfif',
        cat:'candleholder',
        type:'new',
    },
    {
        id:3,
        Name: 'product3',
        price:'15',
        image:'image/p3.avif',
        cat:'necklace',
        type:'new',
    },
    {
        id:4,
        Name: 'product4',
        price:'82',
        image:'image/p4.png',
        cat:'toy',
        type:'new',
    },
    {
        id:5,
        Name: 'product5',
        price:'72',
        image:'image/p5.jpg',
        cat:'carpet',
        type:'featured',
    },
    {
        id:6,
        Name: 'product6',
        price:'100',
        image:'image/p6.jpg',
        cat:'pillow',
        type:'featured',
    },
    {
        id:7,
        Name: 'product7',
        price:'120',
        image:'image/p7.avif',
        cat:'wall_paper',
        type:'featured',
    },
    {
        id:8,
        Name: 'product8',
        price:'26',
        image:'image/p8.jfif',
        cat:'candleholder',
        type:'featured',
    },
    {
        id:9,
        Name: 'product9',
        price:'20',
        image:'image/p9.jpg',
        cat:'necklace',
        type:'top',
    },
    {
        id:10,
        Name: 'product10',
        price:'260',
        image:'image/p10.jfif',
        cat:'table',
        type:'top',
    },
    {
        id:11,
        Name: 'product11',
        price:'36',
        image:'image/p11.jpg',
        cat:'ring',
        type:'top',
    },
    {
        id:12,
        Name: 'product12',
        price:'160',
        image:'image/p12.jfif',
        cat:'table',
        type:'top',
    }
]
export default Homeproduct

